name: ChromElevator Build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build Project
        shell: cmd
        run: |
          make.bat

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ChromElevator-Release
          path: build/chromelevator_x64.exe
